files = ["alt_FIFO_am_full_flag.vhd",
"EB_2_wb_converter.vhd",
"EB_checksum.vhd",
"eb_config_new.vhd",
"EB_CORE.vhd",
"EB_HDR_pkg.vhd",
"EB_RX_CTRL.vhd",
"EB_TX_CTRL.vhd",
"piso_flag.vhd",
"sipo_flag.vhd",
"vhdl_2008_workaround_pkg.vhd",
"WB_bus_adapter_streaming_sg.vhd",
"wishbone_package16.vhd",
"wishbone_package32.vhd",
"xetherbone_core.vhd"];
