# TCL File Generated by Component Editor 10.1
# Tue Mar 08 14:32:00 CET 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | AvalonMasterWBSlave_Bridge "AvalonMasterToWishboneSlaveBridge" v1.0
# | null 2011.03.08.14:32:00
# | 
# | 
# | F:/etherbone-core/AvalonMasterWBSlave_Bridge.vhd
# | 
# |    ./AvalonMasterWBSlave_Bridge.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module AvalonMasterWBSlave_Bridge
# | 
set_module_property NAME AvalonMasterWBSlave_Bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME AvalonMasterToWishboneSlaveBridge
set_module_property TOP_LEVEL_HDL_FILE AvalonMasterWBSlave_Bridge.vhd
set_module_property TOP_LEVEL_HDL_MODULE test
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file AvalonMasterWBSlave_Bridge.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter g_addr_width NATURAL 32
set_parameter_property g_addr_width DEFAULT_VALUE 32
set_parameter_property g_addr_width DISPLAY_NAME g_addr_width
set_parameter_property g_addr_width TYPE NATURAL
set_parameter_property g_addr_width UNITS None
set_parameter_property g_addr_width AFFECTS_GENERATION false
set_parameter_property g_addr_width HDL_PARAMETER true
add_parameter g_data_width NATURAL 32
set_parameter_property g_data_width DEFAULT_VALUE 32
set_parameter_property g_data_width DISPLAY_NAME g_data_width
set_parameter_property g_data_width TYPE NATURAL
set_parameter_property g_data_width UNITS None
set_parameter_property g_data_width AFFECTS_GENERATION false
set_parameter_property g_data_width HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock csi_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 AVS_SL_READ read Input 1
add_interface_port avalon_slave_0 AVS_SL_WRITE write Input 1
add_interface_port avalon_slave_0 AVS_SL_ADDRESS address Input g_addr_width
add_interface_port avalon_slave_0 AVS_SL_WRITEDATA writedata Input g_data_width
add_interface_port avalon_slave_0 AVS_SL_BYTEENABLE byteenable Input g_data_width/8
add_interface_port avalon_slave_0 AVS_SL_ARBITERLOCK arbiterlock Input 1
add_interface_port avalon_slave_0 AVS_SL_WAITREQUEST waitrequest Output 1
add_interface_port avalon_slave_0 AVS_SL_READDATA readdata Output g_data_width
add_interface_port avalon_slave_0 AVS_SL_DATAAVAILABLE dataavailable Output 1
add_interface_port avalon_slave_0 AVS_SL_READYFORDATA readyfordata Output 1
add_interface_port avalon_slave_0 AVS_SL_READDATAVALID readdatavalid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink csi_n_rst reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end WB_ACK_I export Input 1
add_interface_port conduit_end WB_DATA_I export Input g_data_width
add_interface_port conduit_end WB_STALL_I export Input 1
add_interface_port conduit_end WB_STB_O export Output 1
add_interface_port conduit_end WB_CYC_O export Output 1
add_interface_port conduit_end WB_WE_O export Output 1
add_interface_port conduit_end WB_ADDR_O export Output g_addr_width
add_interface_port conduit_end WB_DATA_O export Output g_data_width
add_interface_port conduit_end WB_SEL_O export Output g_data_width/8
# | 
# +-----------------------------------
