files = [
  "eb_main_fsm.vhd",
  "eb_checksum.vhd",
  "eb_config.vhd",
  "eb_slave_core.vhd",
  "eb_hdr_pkg.vhd",
  "eb_rx_ctrl.vhd",
  "eb_tx_ctrl.vhd",
  "etherbone_pkg.vhd",
  "piso_flag.vhd",
  "sipo_flag.vhd",
  "vhdl_2008_workaround_pkg.vhd",
  "WB_bus_adapter_streaming_sg.vhd",
  "eb_usb_slave_core.vhd",
  "xetherbone_core.vhd"];
